### ISSUE TITLE
decreasing versions

### ISSUE THREAD

**Issue by chorny** [hurricup/DTL-Fast#1]
Versions with 2 dots are converted to real numbers. 0.1.1 means 0.001001. So 0.1 > 0.1.1.
Versions with one dot are real numbers. So 0.9 > 0.10.
Best is to delete distributions that have bigger versions that latest (that will help new installations). And upload new distribution with correct version (that will help users that have older version installed).

**Comment by hurricup** [comment]
Thanks, marked pervious versions for deletion.
If i get this right, main release should be 1.5.0 and patches 1.5.1, 1.5.2 etc?

**Comment by chorny** [comment]
You have 1.05 which is same as 1.50.0, so you should use 1.51.0.

**Comment by hurricup** [comment]
I don't get it. Accroding to your first post, there is a difference between 1.5 and 1.5.0 (which is 1.005000)
Is there any RFC or smth to read?

**Comment by chorny** [comment]
http://www.dagolden.com/index.php/369/version-numbers-should-be-boring/
http://search.cpan.org/perldoc?version

**Comment by hurricup** [comment]
Thanks for links and notification. According to version, 1.5.0 is less than 1.5.1
Will use v1.5.0 in release and v1.5.1 in fixes.

Btw, you may run a test: 

```
use Perl::Version;
use version;

foreach my $ver ('1.0.0', 'v1.0.0', '1.5.0', 'v1.5.0', '1.5', 'v1.5', '1.5.1', 'v1.5.1')
{
    printf " Perl::Version for %6s is %s\n", $ver, Perl::Version->new($ver)->numify;
    printf "version->parse for %6s is %s\n", $ver, version->parse($ver)->numify;
}
```
