### ISSUE TITLE
Can't seem to install...

### ISSUE THREAD

**Issue by jjn1056** [hurricup/DTL-Fast#2]
Hi,

When I try to install you module I just get errors.  I know my internet is good (can download other things just fine):

johns-MBP:Vota jnapiorkowski$ cpanm DTL::Fast
--> Working on DTL::Fast
Fetching http://www.cpan.org/authors/id/H/HU/HURRICUP/DTL-Fast-1.05.tar.gz ... FAIL
! Download http://www.cpan.org/authors/id/H/HU/HURRICUP/DTL-Fast-1.05.tar.gz failed. Retrying ... 
! Download http://www.cpan.org/authors/id/H/HU/HURRICUP/DTL-Fast-1.05.tar.gz failed. Retrying ... 
! Download http://www.cpan.org/authors/id/H/HU/HURRICUP/DTL-Fast-1.05.tar.gz failed. Retrying ... 
! Failed to download http://www.cpan.org/authors/id/H/HU/HURRICUP/DTL-Fast-1.05.tar.gz
! Failed to fetch distribution DTL-Fast-1.05

Maybe your version declaration is a bit different?  I see in the code 

```
 our $VERSION = 'v1.05.6';
```

Maybe it would be more compatible to use a more old style declaration?  I know the DBIx::Class people do like the following and that seems to work no matter what system or Perl version I have to use:

```
 our $VERSION;
 $VERSION = '0.082810';
 $VERSION = eval $VERSION if $VERSION =~ /_/; # numify for warning-free dev releases
```

I usually just cargo cult this approach since its bullet proof.  Let me know what you think.  great work BTW, and very interested in using this on my new website project.

**Comment by hurricup** [comment]
Ye, i know that i've screwed with versioning. Generally, i'ts my first properly made public module.
Just uploaded with version 1.600, hope this will help.

And don't forget to report bugs :)

**Comment by hurricup** [comment]
Smth strange is going on. Now cpan DTL::Fast says that there is no such module. Seems i don't get smth...

**Comment by jjn1056** [comment]
It installed for me this morning:

johns-MBP:Vota jnapiorkowski$ cpanm DTL::Fast
--> Working on DTL::Fast
Fetching http://www.cpan.org/authors/id/H/HU/HURRICUP/DTL-Fast-1.600.tar.gz ... OK
Configuring DTL-Fast-1.600 ... OK
==> Found dependencies: URI::Escape::XS
--> Working on URI::Escape::XS
Fetching http://www.cpan.org/authors/id/D/DA/DANKOGAI/URI-Escape-XS-0.12.tar.gz ... OK
Configuring URI-Escape-XS-0.12 ... OK
Building and testing URI-Escape-XS-0.12 ... OK
Successfully installed URI-Escape-XS-0.12
Building and testing DTL-Fast-1.600 ... OK
Successfully installed DTL-Fast-1.600
2 distributions installed

maybe the indexer was a bit slow, sometimes it might take an hour for things to get distributed properly.

I'll be playing with this today, I"m using it on a new catalyst project, so there probably will be a Catalyst::View for this sooner or later.  Thanks, I'll let you know if I hit snags.

I'm choosing this since my front end people are not so familiar with template toolkit and this seems a lot faster.  Welcome to CPAN!

**Comment by hurricup** [comment]
Yep, seems version reset && reindexing helped.
Thanks again.
